name: flutter_riverpod_base
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.16
  built_value: ^8.1.4
  dio: ^4.0.6
  package_info_plus: ^3.0.3
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.7
  flutter_svg: ^1.0.3
  lottie: ^1.2.1
  path_provider: ^2.0.13
  app_installer: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  json_serializable: ^6.1.4
  freezed: ^1.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: iran_sans_x
      fonts:
        - asset: assets/fonts/iran_sans_x_ultra_light.otf
          weight: 100
        - asset: assets/fonts/iran_sans_x_thin.otf
          weight: 200
        - asset: assets/fonts/iran_sans_x_light.otf
          weight: 300
        - asset: assets/fonts/iran_sans_x_regular.otf
          weight: 400
        - asset: assets/fonts/iran_sans_x_medium.otf
          weight: 500
        - asset: assets/fonts/iran_sans_x_semi_bold.otf
          weight: 600
        - asset: assets/fonts/iran_sans_x_bold.otf
          weight: 700
        - asset: assets/fonts/iran_sans_x_extra_bold.otf
          weight: 800
        - asset: assets/fonts/iran_sans_x_black.otf
          weight: 900